### ISSUE TITLE
JOSS#4590 no plain-text LICENSE file

### ISSUE THREAD

**Issue by wimvanderbauwhede** [ajohnson-uoregon/clang-rewrite-only#2]
[openjournals/joss-reviews#4590](https://github.com/openjournals/joss-reviews/issues/4590)

There is no plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license at top level or in the clang-rewrite-only folder, I checked the master and joss22 branches. This is a JOSS requirement so please add a  LICENSE file.

**Comment by ajohnson-uoregon** [comment]
A license file and license headers in all the code files have been added: https://github.com/ajohnson-uoregon/clang-rewrite-only/blob/joss22/clang-tools-extra/clang-rewrite/LICENSE.txt

LLVM as a whole is licensed under [Apache 2.0 with LLVM Exceptions](https://llvm.org/LICENSE.txt), so I chose to place this under the same license since it'll eventually (hopefully) get upstreamed into LLVM. I don't see that in the OSI approved list, but since it's essentially a more permissive version of Apache 2.0 is this okay or should I change it to vanilla Apache 2.0?

**Comment by wimvanderbauwhede** [comment]
[openjournals/joss-reviews#4590](https://github.com/openjournals/joss-reviews/issues/4590)

@ajohnson-uoregon
I think the LLVM project requires either the "Apache 2.0 License with LLVM exceptions" or the old NCSA license, I don't think vanilla Apache 2.0 is acceptable.

For JOSS your license has to be OSI approved. Can you maybe use the NCSA license? https://opensource.org/licenses/UoI-NCSA.php

**Comment by ajohnson-uoregon** [comment]
Updated to NCSA license: 225a318956e3586d and [c92ee871](https://github.com/ajohnson-uoregon/llvm-project/commit/ca5fed1db5c23c031fcbb6c8d8d26ab7c2da8253).

**Comment by wimvanderbauwhede** [comment]
[openjournals/joss-reviews#4590](https://github.com/openjournals/joss-reviews/issues/4590)

@ajohnson-uoregon Thanks, we can finalise the review now
